### PR TITLE
users should be able to update their notes

### PR DESCRIPTION
**Pull request by vic3king**
#### What does this PR do?
users should be able to update their notes
#### Description of Task to be completed?
- creates an endpoint for updating notes
- validate endpoints
- write tests for the endpoint
#### How should this be manually tested?
- clone repo
- checkout branch ft-update-notes 
- npm run start:dev
- make a PUT request to notes/:id.
#### Any background context you want to provide?
NA
#### What are the relevant pivotal tracker stories?
NA

### CODE REVIEW

**Comment by sojida** [comment]
Great work, please resolve this merge conflict.

**Comment by vic3king** [comment]
> Great work, please resolve this merge conflict.

Resolved, Thank you.

**Review by Chiazokam — APPROVED** [review]
Good to go!!!!

Learned something new: 'to.deep.equal()' in tests.

**Review by amaechi-chuks — COMMENTED** [review]
Good Job. You can merge it

**Review by sojida — APPROVED** [review]

**Comment by vic3king** [comment]
> Good Job. You can merge it

Great.

**Pull request merged**
