### PR TITLE
[bug-fix]: fix bug on getOneNote

### PR DESCRIPTION
**Pull request by sojida**
#### What bug does this PR do?
Fix a bug in get one note

#### Description of task to be done
- update `.env` file with example.env

#### screenshot
Bug 
Screenshot 2019-03-16 at 3 54 24 PM

Fix
Screenshot 2019-03-16 at 3 56 29 PM

### CODE REVIEW

**Comment by sojida** [comment]
Any update?

**Comment by sojida** [comment]
Please review if you see this!

**Review by vic3king — CHANGES_REQUESTED** [review]
@sojida Thank you for fixing this issue. please remove the commented out code in the Routes index file and then you can merge

**Review by Chiazokam — APPROVED** [review]
I'm sorry for the delay. Great Observation. Please go ahead and merge

**Review by Chiazokam — APPROVED** [review]

**Review by vic3king — APPROVED** [review]

**Pull request merged**
